name: disney_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-374.1.beta <3.0.0'

dependencies:
  cloud_firestore: ^4.3.2
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.2
  firebase_core: ^2.5.0
  firebase_storage: ^11.0.11
  flutter:
    sdk: flutter
  flutter_gen: ^5.3.1
  flutter_hooks: ^0.18.3
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.1.3+1
  flutter_picker: ^2.1.0
  flutter_rating_bar: ^4.0.1
  flutter_riverpod: ^2.2.0
  flutter_secure_storage: ^8.0.0
  font_awesome_flutter: ^10.5.0
  freezed_annotation: ^2.4.1
  google_fonts: ^4.0.3
  hooks_riverpod: ^2.1.3
  image_picker: ^0.8.6+1
  intl: ^0.18.0
  loading_animation_widget: ^1.2.0+4
  path_provider: ^2.1.0
  screenshot: ^2.1.0
  share_plus: ^7.1.0
  shared_preferences: ^2.2.0
  skeletonizer: ^0.7.0
  url_launcher: ^6.1.12

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  mockito: ^5.2.0
  riverpod: ^2.1.3

flutter_icons:
  android: false
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: '#FFF422'
  adaptive_icon_foreground: "assets/icon/icon.png"

flutter_native_splash:
  color: '#DBEBFF'
  image: 'assets/splash/splash.png'
  color_dark: '#DBEBFF'
  image_dark: 'assets/splash/splash.png'
  fullscreen: true
  android_12:
    icon_background_color: '#DBEBFF'
    image: 'assets/splash/splash.png'
    icon_background_color_dark: '#DBEBFF'
    image_dark: 'assets/splash/splash.png'

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/header/
    - assets/images/

flutter_gen:
  output: lib/gen/
  lineLength: 80
  integrations:
    flutter_svg: true